import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.sass";
import Navigation from "./ui/navigation/naviagtion";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MY.SITE",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
          <Link href={"/"} className={styles.header__logo}>
            My.Site
          </Link>
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
